### PR TITLE
Fix HDF5 deprecations

### PR DESCRIPTION
**Pull request by sloede**

### CODE REVIEW

**Comment by ranocha** [comment]
I think we need to lower version of HDF5 in Trixi, Trixi2Vtk, and Trixi2Img to `v0.14` to make everything work in general.

**Comment by ranocha** [comment]
Additionally, we will probably need to merge the PR bumping the lower version of Trixi to `v0.3` first to get the increased version bounds for HDF5 here.

**Comment by sloede** [comment]
> I think we need to lower version of HDF5 in Trixi, Trixi2Vtk, and Trixi2Img to `v0.14` to make everything work in general.

Is what I did in #23 what you meant?

**Comment by ranocha** [comment]
> Is what I did in #23 what you meant?

Yes, but it needs additional changes for Trixi `v0.3`. I'm working on that in #21.

**Review by ranocha — APPROVED** [review]
LGTM and can be merged when the tests pass.

**Pull request merged**
