### PR TITLE
introduce `get_default_nvisnodes_mesh`

### PR DESCRIPTION
**Pull request by ranocha**
This should hopefully fix the issue reported in #55. The idea is to still use `nvisnodes` even when visualizing only a mesh file by introducing another function `get_default_nvisnodes_mesh` and renaming the previous `get_default_nvisnodes` to `get_default_nvisnodes_solution`.

### CODE REVIEW

**Review by sloede — APPROVED** [review]
Seems to make sense - thanks for fixing this so quickly!

**Review by sloede — APPROVED** [review]
LGTM! Thanks for fixing!

**Comment by ranocha** [comment]
CI on Windows runs out of memory:
https://github.com/trixi-framework/Trixi2Vtk.jl/actions/runs/3563378478/jobs/5986095285#step:6:1471

Merge anyways, @sloede?

**Comment by sloede** [comment]
I'd say rerun once and try again?

**Comment by sloede** [comment]
Can imho be merged despite the drop in coverage (out of 8 new lines, only 6 are covered).

**Pull request merged**
