### PR TITLE
allow v0.17 of HDF5.jl

### PR DESCRIPTION
**Pull request by ranocha**
CompatHelper didn't run but I re-enabled it. Nevertheless, it would be nice to get this merged soon.

Closes #72

### CODE REVIEW

**Comment by jlchan** [comment]
Are the test failure spurious?

**Comment by ranocha** [comment]
No, it errors since we enabled a lot of warnings - and get some from calling a deprecated method of ProgressMeter.jl. Should hopefully be fixed in #70.

**Review by jlchan — APPROVED** [review]

**Comment by ranocha** [comment]
Do not merge this right now - CI doesn't pick up the new version of HDF5.jl. I will look into it

**Comment by ranocha** [comment]
Now, CI on Julia v1.9 uses the new version 0.17 of HDF5.jl. Let's keep fingers crossed that tests pass

**Pull request merged**
