### PR TITLE
fix VTK output of TreeMesh levels (celldata)

### LINKED ISSUE #40: AMR levels do not show correctly in Paraview
I am not sure if this is a Trixi Bug, or a Trixi2Vtk Bug. However, in the simulation of the new colliding flow elixir

` trixi_include("examples/tree_2d_dgsem/elixir_euler_colliding_flow_amr.jl", tspan=(0.0, 25.0))`

I observe weird display of levels.

I am using trixi2vtk on the h5 file to generate the solution file and the celldata file. The celldata file looks good in general (amr indicator, shock captuturing indicator), however the levels are broken with some garbage numbers shown. Here is a screenshot of Paraview, looking at the levels. I also display the grid, which clearly shows there is AMR with different levels active...

grafik

### PR DESCRIPTION
**Pull request by ranocha**
Could you please confirm that this fixes the bug you reported, @gregorgassner?

Closes #40

### CODE REVIEW

**Review by sloede — APPROVED** [review]
Good catch! Can be merged IMHO once @gregorgassner confirms this fixes his issues.

**Comment by ranocha** [comment]
Can we merge this, @sloede?

**Review by sloede — DISMISSED** [review]
I confirmed that the behavior observed in #40 is fixed. Can be merged. Thanks again @ranocha

**Comment by ranocha** [comment]
```
Test Summary:                   | Pass  Fail  Total
2D                              |   18     2     20
  TreeMesh                      |    9            9
  StructuredMesh                |    3     2      5
    waving flag                 |    1     1      2
    waving flag (supersampling) |    1     1      2
  UnstructuredMesh2D            |    3            3
  P4estMesh                     |    3            3
```
Honestly?

**Comment by ranocha** [comment]
Could you please take care of that, @sleode? I don't know whether it's a real regression or just some artifact caused by improper testing...

**Comment by sloede** [comment]
> Could you please take care of that, @sleode? I don't know whether it's a real regression or just some artifact caused by improper testing...

Was there a change lately in Trixi that could affect `StructuredMesh` results? That's the only explanation I currently have.

**Comment by ranocha** [comment]
> Was there a change lately in Trixi that could affect `StructuredMesh` results? That's the only explanation I currently have.

I'm not sure. It uses advection on the waving flag in 2D - that's a rather simple setup. But I enabled FMA support in StaticArrays.jl in the time period of interest. Thus, computations like `contravariant_flux1 = Ja11 * flux1 + Ja12 * flux2` in the volume terms might have changed by floating point precision...

**Comment by sloede** [comment]
Yes, it's a horrible, horrible way we are testing this package right now. Since the update frequency here is low, essentially each time we have a new PR we need to update the file hashes since almost always "something" changes. We need something like a proper `TestVTK.jl` package, I think, to make automated testing more useful.

I put it on the agenda for the next meeting to come up with possible solutions.

**Review by sloede — APPROVED** [review]

**Pull request merged**
